import { Document, model, ObjectId, Schema } from "mongoose";

const schema = new Schema(
  {
    name: { type: String},
    email: { type: String},
    password: { type: String },
    address: { type: String },
    token: { type: String },
    contact: { type: Number },
    profile_picture: { type: String },
    userType:{ type: String },
    signature: { type: String },
    country_code: { type: Number },
    landline: { type: Number },
    otp: { type: Number,default:0 },
    Description: { type: String },
    validContact: { type: Boolean, default: false },
    whatsappNo: { type: Number, unique: false }, 
    createrId: { type: Schema.Types.ObjectId, ref: "userDetail" },
    bankDetailId: { type: Schema.Types.ObjectId, ref: "bank_details" },
    isBlackList: { type: Boolean, default: false },
    gstNo: { type: String },
    gstImage: [{ type: String }],
    aadharCardNo: { type: Number },
    aadharCardImage: [{ type: String }],
    panCardNo: { type: String },
    panCardImage: [{ type: String }],
    registrationNo: { type: String },
    registrationImage: [
      {
        type: String,
      },
    ],
    country: { type: String, default: "India" },
    isActive: { type: Boolean, default: false },
    contact_verify: { type: Boolean, default: false },
    email_verify: { type: Boolean, default: false },
    isacademyOwnerVerified: { type: Boolean, default: false },
    isRequestSend: { type: Boolean, default: false },
    isRequestAccept: { type: Boolean, default: false },
    isRequestReject: { type: Boolean, default: false },
    rejectDescription: { type: String },
    isPublished: { type: Boolean, default: false },
    isDeleted: { type: Boolean, default: false },
  },
  {
    timestamps: true,
  }
);

export interface IAcademyOwner extends Document {
    name: String,
    email: String,
    password: String,
    address: String,
    token: String,
    userType: String,
    contact: String,
    profile_picture: String,
    signature: String,
    country_code: String,
    landline: String,
    Description: String,
    validContact: Boolean,
    whatsappNo: Number, 
    otp: Number, 
    createrId:ObjectId,
    bankDetailId: ObjectId,
    isBlackList: Boolean,
    gstNo: String,
    gstImage: [String],
    aadharCardNo: { type: Number },
    aadharCardImage: [String],
    panCardNo: String,
    panCardImage: [String],
    registrationNo: String,
    registrationImage: [
        String,
    ],
    country: String,
    isActive: Boolean,
    contact_verify: Boolean,
    email_verify: Boolean,
    isacademyOwnerVerified: Boolean,
    isRequestSend: Boolean,
    isRequestAccept: Boolean,
    isRequestReject: Boolean,
    rejectDescription: String,
    isPublished: Boolean,
    isDeleted: Boolean,
}
// userDetail

export default model<IAcademyOwner>("academy_owner", schema);
